_instantiator: lightning.pytorch.cli.instantiate_module
batch_size: 64
data_manager:
  class_path: probts.DataManager
  init_args:
    auto_search: false
    context_length: 96
    context_length_factor: 1
    continuous_sample: false
    data_path: null
    dataset: etth1
    freq: null
    history_length: null
    multivariate: true
    path: ./datasets
    prediction_length: 96
    scaler: standard
    split_val: true
    test_ratio: 0.2
    test_rolling_length: 96
    timeenc: 1
    train_ctx_len: null
    train_pred_len_list: null
    train_ratio: 0.7
    val_ctx_len: null
    val_pred_len_list: null
    var_specific_norm: true
forecaster:
  class_path: probts.model.forecaster.prob_forecaster.k2vae.k2VAEModel
  init_args:
    activation: relu
    autoregressive: false
    context_length: 96
    d_ff: 256
    d_model: 128
    dataset: etth1
    dropout: 0.1
    dynamic_dim: 128
    e_layers: 1
    factor: 3
    feat_idx_emb_dim: 1
    freq: H
    global_mean: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk4Njc2MzA1NzA5NjY0cQJYAwAAAGNwdXEDSwdOdHEEUS6AAl1xAFgOAAAAOTg2
        NzYzMDU3MDk2NjRxAWEuBwAAAAAAAAD8Af5AslgBQHuNokAJBj8/ZQgyQBHYST+uBolB
    - 0
    - !!python/tuple
      - 7
    - !!python/tuple
      - 1
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    hidden_dim: 256
    hidden_layers: 3
    history_length: 264
    init_kalman: identity
    init_koopman: dynamic
    lags_list:
    - 1
    - 24
    - 168
    multistep: true
    n_heads: 4
    no_training: false
    patch_len: 24
    prediction_length: 96
    sample_schedule: 20
    target_dim: 7
    time_feat_dim: 4
    train_pred_len_list: &id001
    - 96
    use_feat_idx_emb: false
    use_lags: false
    use_scaling: false
    use_time_feat: false
    weight_beta: 0.01
learning_rate: 0.001
load_from_ckpt: null
lr_scheduler_config: null
num_samples: 100
num_workers: 8
optimizer_config: null
quantiles_num: 20
sampling_weight_scheme: none
scaler: !!python/object:probts.data.data_utils.data_scaler.StandardScaler
  epsilon: 1.0e-09
  mean: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApEb3VibGVTdG9y
      YWdlCnEBWA4AAAA5ODY3NjEyNTIzODc2OHECWAMAAABjcHVxA0sHTnRxBFEugAJdcQBYDgAAADk4
      Njc2MTI1MjM4NzY4cQFhLgcAAAAAAAAAob3UgD/AH0BQ+rRQFisAQEqfbGKvURRATjHqNcHg5z+y
      zlWjDEEGQBv+ggsCO+k//jY3wtUgMUA=
  - 0
  - !!python/tuple
    - 7
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  scale: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApEb3VibGVTdG9y
      YWdlCnEBWA4AAAA5ODY3NjMwODAwMzYxNnECWAMAAABjcHVxA0sHTnRxBFEugAJdcQBYDgAAADk4
      Njc2MzA4MDAzNjE2cQFhLgcAAAAAAAAAmfkAkplAF0AALDE1yLgAQLkCeFqSExZAxDa9+ufS/j8X
      ThRpl2DwPxD5IoQyK+Q/DcuepKJaIkA=
  - 0
  - !!python/tuple
    - 7
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  var_specific: true
test_batch_size: 32
train_pred_len_list: *id001
